import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

export const FaqAccordion: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: 'Why can’t tokenized stocks simply use pump-style bonding curves?',
      a: 'Pump-style curves are hyperbolic exponential curves engineered for memecoins seeking 100x speculative blowups. For tokenized equities (e.g. $125 NVDA stock), an exponential curve creates artificial 50x price surges that completely break the underlying legal custody and arbitrage link to the real stock. Furthermore, 95% of early curve supply gets sniped by bots in Block 0. EquiLaunch uses Bounded Sigmoid curves with reference NAV anchors to ensure realistic valuation bands and minimal slippage.',
    },
    {
      q: 'How does the decaying anti-snipe fee eliminate MEV bot profitability?',
      a: 'At pool creation (Genesis block), the trading fee starts high (4.5%–6.0%). If a front-running bot bundles multiple transactions to corner the initial supply, their profit margin is mathematically wiped out by the initial fee. As legitimate syndicate volume participates and the pool matures, the fee smoothly decays down to 0.20% at graduation.',
    },
    {
      q: 'What is the advantage of migrating into BOTH DAMM v2 and DLMM?',
      a: 'A single standard AMM cannot satisfy both long-term passive liquidity and high-frequency equity trading. EquiLaunch splits graduated liquidity: 60% enters Meteora DAMM v2 to provide permanent protocol-owned liquidity where dynamic volatility fees compound into syndicate reserves; 40% enters Meteora DLMM with 51 concentrated bins centered tightly around the discovery price (15 bps bin step) to give institutional market makers tight bid-ask spreads.',
    },
    {
      q: 'Can builders export and deploy these curves using Meteora Invent CLI?',
      a: 'Yes! EquiLaunch includes a built-in Curve Architect and Preset Studio. You can customize the NAV anchor, ceiling multiplier, floor reserve, and fee decay schedule, and export a ready-to-run YAML manifest compatible with `invent dbc:create` or copy production TypeScript SDK scripts using `@meteora-ag/dynamic-bonding-curve-sdk`.',
    },
    {
      q: 'Who receives the fees generated by the Meteora DAMM v2 pool?',
      a: 'The LP tokens from the 60% DAMM v2 allocation are permanently assigned to the Tokenized Stock Syndicate Vault. Accumulated dynamic trading fees can be automatically distributed as on-chain dividends to equity holders or reinvested into deepening the underwriter liquidity floor.',
    },
  ];

  return (
    <div className="max-w-3xl mx-auto space-y-4 py-6">
      <div className="text-center space-y-2 mb-6">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-800 border border-slate-700 text-slate-300 text-xs font-mono font-semibold">
          <HelpCircle className="w-3.5 h-3.5 text-teal-400" />
          <span>Frequently Asked Questions</span>
        </div>
        <h2 className="text-2xl font-bold text-white tracking-tight">
          Everything You Need to Know
        </h2>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, idx) => {
          const isOpen = openIndex === idx;
          return (
            <div
              key={idx}
              className={`rounded-2xl border transition-all duration-200 overflow-hidden ${
                isOpen
                  ? 'bg-slate-900/90 border-teal-500/40 shadow-lg'
                  : 'bg-slate-900/40 border-slate-800 hover:border-slate-700'
              }`}
            >
              <button
                onClick={() => setOpenIndex(isOpen ? null : idx)}
                className="w-full p-4 text-left flex items-center justify-between gap-4 cursor-pointer select-none"
              >
                <span className="text-sm font-semibold text-white">{faq.q}</span>
                <ChevronDown
                  className={`w-4 h-4 text-teal-400 shrink-0 transition-transform duration-200 ${
                    isOpen ? 'rotate-180' : ''
                  }`}
                />
              </button>

              {isOpen && (
                <div className="px-4 pb-4 text-xs text-slate-300 leading-relaxed font-sans border-t border-slate-800/60 pt-3 animate-in fade-in duration-200">
                  {faq.a}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
