import { DBCPreset, EquityAsset } from '../types';

export function generateMeteoraInventCliConfig(assetOrPreset: Partial<EquityAsset & DBCPreset>): string {
  const symbol = assetOrPreset.symbol || 'xEQUITY';
  const name = assetOrPreset.name || 'Tokenized Equity';
  const targetUsdc = assetOrPreset.graduationTargetUsdc || assetOrPreset.graduationThreshold || 250000;
  const initialPrice = assetOrPreset.initialPrice || 50;
  const maxPrice = assetOrPreset.maxPrice || 120;
  const startFeeBps = Math.round((assetOrPreset.antiSnipeMaxFeePercent || 5) * 100);
  const baseFeeBps = Math.round((assetOrPreset.baseFeePercent || 0.25) * 100);
  const curveType = assetOrPreset.curveType || 'bounded_sigmoid';

  return `# ==============================================================
# Meteora DBC (Dynamic Bonding Curve) Configuration
# Generated by EquiLaunch for Tokenized Equities & RWAs
# ==============================================================

name: "${name}"
symbol: "${symbol}"
decimals: 6
totalSupply: 1000000

curveConfig:
  type: "${curveType}"
  quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # USDC
  initialPrice: ${initialPrice}
  maxPrice: ${maxPrice}
  graduationCapUsdc: ${targetUsdc}
  underwritingFloorReservePercent: 25.0

feeSchedule:
  type: "decaying_anti_snipe"
  initialFeeBps: ${startFeeBps} # ${startFeeBps / 100}% at Genesis (blocks 0-100)
  terminalFeeBps: ${baseFeeBps} # ${baseFeeBps / 100}% Post-Discovery
  decayHalfLifeBlocks: 500

migrationConfig:
  targetDammV2:
    allocationRatio: 0.60 # 60% permanent compounding liquidity
    dynamicFeeEnabled: true
    minFeeBps: 20
    maxFeeBps: 250
  targetDlmm:
    allocationRatio: 0.40 # 40% concentrated liquidity
    binStepBps: 15 # 0.15% per bin
    concentrationBins: 51
    strategy: "SpotBalanced"

# Execute launch on Solana Mainnet or Devnet via Meteora Invent CLI:
# > invent dbc:create --config ./equilaunch-${symbol.toLowerCase()}.yaml --keypair ~/.config/solana/id.json
`;
}

export function generateMeteoraTypeScriptSdkCode(assetOrPreset: Partial<EquityAsset & DBCPreset>): string {
  const symbol = assetOrPreset.symbol || 'xEQUITY';
  const targetUsdc = assetOrPreset.graduationTargetUsdc || assetOrPreset.graduationThreshold || 250000;
  const initialPrice = assetOrPreset.initialPrice || 50;
  const maxPrice = assetOrPreset.maxPrice || 120;

  return `import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { 
  DynamicBondingCurveClient, 
  CurveType, 
  FeeScheduleType 
} from "@meteora-ag/dynamic-bonding-curve-sdk";
import { DammV2Client } from "@meteora-ag/damm-v2-sdk";
import DLMM from "@meteora-ag/dlmm";

/**
 * EquiLaunch: Programmatic Meteora DBC Tokenized Stock Launch
 * Pairs Tokenized Stock with USDC using Bounded Sigmoid Curve
 */
async function launchTokenizedEquityDbc(
  connection: Connection,
  payer: Keypair
) {
  const dbcClient = new DynamicBondingCurveClient(connection);

  // 1. Initialize DBC Pool with Bounded Equity Curve
  console.log("Initializing Meteora DBC Pool for ${symbol}...");
  const { poolAddress, txSignature } = await dbcClient.createPool({
    payer: payer.publicKey,
    tokenMintMetadata: {
      name: "${assetOrPreset.name || 'Tokenized Stock'}",
      symbol: "${symbol}",
      uri: "https://arweave.net/metadata-uri",
      decimals: 6,
    },
    quoteMint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // USDC
    curveParameters: {
      curveType: CurveType.SigmoidBounded,
      initialPriceUsdc: ${initialPrice},
      targetCapUsdc: ${targetUsdc},
      maxCeilingPriceUsdc: ${maxPrice},
    },
    dynamicFeeConfig: {
      type: FeeScheduleType.DecayingAntiSnipe,
      initialFeeBps: 500, // 5%
      decayHalflifeBlocks: 400,
      baseFeeBps: 25, // 0.25%
    },
    migrationRules: {
      dammV2Ratio: 0.60,
      dlmmRatio: 0.40,
      dlmmBinStep: 15,
    }
  });

  console.log(\`DBC Launch Successful! Pool Address: \${poolAddress.toBase58()}\`);
  return poolAddress;
}
`;
}
